/*
 * Browse API
 * <p>The Browse API has the following resources:</p>   <ul> <li><b> item_summary: </b> Lets shoppers search for specific items by keyword, GTIN, category, charity, product, image </b><a href=\"/api-docs/static/versioning.html#experimental \" target=\"_blank\"><img src=\"/cms/img/docs/experimental-icon.svg\" class=\"legend-icon experimental-icon\" alt=\"Experimental Method\" title=\"Experimental Method\" />(Experimental Method)</a>, or item aspects and refine the results by using filters, such as aspects, compatibility, and fields values, or UI parameters.</li>   <li><b> item: </b> <ul><li>Lets you retrieve the details of a specific item or all the items in an item group, which is an item with variations such as color and size and check if a product is compatible with the specified item, such as if a specific car is compatible with a specific part.</li> <li>Provides a bridge between the eBay legacy APIs, such as <b> Finding</b>, and the RESTful APIs, which use different formats for the item IDs.</li>  </ul> </li>  </ul>       <p>The <b> item_summary</b>, <b> search_by_image</b>, and <b> item</b> resource calls require an <a href=\"/api-docs/static/oauth-client-credentials-grant.html\">Application access token</a>.</p>
 *
 * OpenAPI spec version: v1.19.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.ebuyer.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.util.Objects;

/**
 * This container describes an add-on service that may be selected for an item or that may apply automatically. A charge may be associated with the add-on service.
 */
@Schema(description = "This container describes an add-on service that may be selected for an item or that may apply automatically. A charge may be associated with the add-on service.")
@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-25T17:50:03.851347329Z[GMT]")

public class AddonService {
  @SerializedName("selection")
  private String selection = null;

  @SerializedName("serviceFee")
  private ConvertedAmount serviceFee = null;

  @SerializedName("serviceId")
  private String serviceId = null;

  @SerializedName("serviceType")
  private String serviceType = null;

  public AddonService selection(String selection) {
    this.selection = selection;
    return this;
  }

   /**
   * This field indicates whether the add-on service must be selected for the item. For implementation help, refer to &lt;a href&#x3D;&#x27;https://developer.ebay.com/api-docs/buy/browse/types/gct:AddonServiceSelectionEnum&#x27;&gt;eBay API documentation&lt;/a&gt;
   * @return selection
  **/
  @Schema(description = "This field indicates whether the add-on service must be selected for the item. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/buy/browse/types/gct:AddonServiceSelectionEnum'>eBay API documentation</a>")
  public String getSelection() {
    return selection;
  }

  public void setSelection(String selection) {
    this.selection = selection;
  }

  public AddonService serviceFee(ConvertedAmount serviceFee) {
    this.serviceFee = serviceFee;
    return this;
  }

   /**
   * Get serviceFee
   * @return serviceFee
  **/
  @Schema(description = "")
  public ConvertedAmount getServiceFee() {
    return serviceFee;
  }

  public void setServiceFee(ConvertedAmount serviceFee) {
    this.serviceFee = serviceFee;
  }

  public AddonService serviceId(String serviceId) {
    this.serviceId = serviceId;
    return this;
  }

   /**
   * The ID number of the add-on service.
   * @return serviceId
  **/
  @Schema(description = "The ID number of the add-on service.")
  public String getServiceId() {
    return serviceId;
  }

  public void setServiceId(String serviceId) {
    this.serviceId = serviceId;
  }

  public AddonService serviceType(String serviceType) {
    this.serviceType = serviceType;
    return this;
  }

   /**
   * The type of add-on service, such as AUTHENTICITY_GUARANTEE. For implementation help, refer to &lt;a href&#x3D;&#x27;https://developer.ebay.com/api-docs/buy/browse/types/gct:AddonServiceTypeEnum&#x27;&gt;eBay API documentation&lt;/a&gt;
   * @return serviceType
  **/
  @Schema(description = "The type of add-on service, such as AUTHENTICITY_GUARANTEE. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/buy/browse/types/gct:AddonServiceTypeEnum'>eBay API documentation</a>")
  public String getServiceType() {
    return serviceType;
  }

  public void setServiceType(String serviceType) {
    this.serviceType = serviceType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddonService addonService = (AddonService) o;
    return Objects.equals(this.selection, addonService.selection) &&
        Objects.equals(this.serviceFee, addonService.serviceFee) &&
        Objects.equals(this.serviceId, addonService.serviceId) &&
        Objects.equals(this.serviceType, addonService.serviceType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(selection, serviceFee, serviceId, serviceType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddonService {\n");
    
    sb.append("    selection: ").append(toIndentedString(selection)).append("\n");
    sb.append("    serviceFee: ").append(toIndentedString(serviceFee)).append("\n");
    sb.append("    serviceId: ").append(toIndentedString(serviceId)).append("\n");
    sb.append("    serviceType: ").append(toIndentedString(serviceType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
