/*
 * Browse API
 * <p>The Browse API has the following resources:</p>   <ul> <li><b> item_summary: </b> Lets shoppers search for specific items by keyword, GTIN, category, charity, product, image </b><a href=\"/api-docs/static/versioning.html#experimental \" target=\"_blank\"><img src=\"/cms/img/docs/experimental-icon.svg\" class=\"legend-icon experimental-icon\" alt=\"Experimental Method\" title=\"Experimental Method\" />(Experimental Method)</a>, or item aspects and refine the results by using filters, such as aspects, compatibility, and fields values, or UI parameters.</li>   <li><b> item: </b> <ul><li>Lets you retrieve the details of a specific item or all the items in an item group, which is an item with variations such as color and size and check if a product is compatible with the specified item, such as if a specific car is compatible with a specific part.</li> <li>Provides a bridge between the eBay legacy APIs, such as <b> Finding</b>, and the RESTful APIs, which use different formats for the item IDs.</li>  </ul> </li>  </ul>       <p>The <b> item_summary</b>, <b> search_by_image</b>, and <b> item</b> resource calls require an <a href=\"/api-docs/static/oauth-client-credentials-grant.html\">Application access token</a>.</p>
 *
 * OpenAPI spec version: v1.19.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.ebuyer.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * The type that defines the fields for the name/value pairs for the aspects of the product. For example: BRAND/Apple
 */
@Schema(description = "The type that defines the fields for the name/value pairs for the aspects of the product. For example: BRAND/Apple")
@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-25T17:50:03.851347329Z[GMT]")

public class Aspect {
  @SerializedName("localizedName")
  private String localizedName = null;

  @SerializedName("localizedValues")
  private List<String> localizedValues = null;

  public Aspect localizedName(String localizedName) {
    this.localizedName = localizedName;
    return this;
  }

   /**
   * The text representing the name of the aspect for the name/value pair, such as Brand.
   * @return localizedName
  **/
  @Schema(description = "The text representing the name of the aspect for the name/value pair, such as Brand.")
  public String getLocalizedName() {
    return localizedName;
  }

  public void setLocalizedName(String localizedName) {
    this.localizedName = localizedName;
  }

  public Aspect localizedValues(List<String> localizedValues) {
    this.localizedValues = localizedValues;
    return this;
  }

  public Aspect addLocalizedValuesItem(String localizedValuesItem) {
    if (this.localizedValues == null) {
      this.localizedValues = new ArrayList<String>();
    }
    this.localizedValues.add(localizedValuesItem);
    return this;
  }

   /**
   * The text representing the value of the aspect for the name/value pair, such as Apple.
   * @return localizedValues
  **/
  @Schema(description = "The text representing the value of the aspect for the name/value pair, such as Apple.")
  public List<String> getLocalizedValues() {
    return localizedValues;
  }

  public void setLocalizedValues(List<String> localizedValues) {
    this.localizedValues = localizedValues;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Aspect aspect = (Aspect) o;
    return Objects.equals(this.localizedName, aspect.localizedName) &&
        Objects.equals(this.localizedValues, aspect.localizedValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(localizedName, localizedValues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Aspect {\n");
    
    sb.append("    localizedName: ").append(toIndentedString(localizedName)).append("\n");
    sb.append("    localizedValues: ").append(toIndentedString(localizedValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
