/*
 * Browse API
 * <p>The Browse API has the following resources:</p>   <ul> <li><b> item_summary: </b> Lets shoppers search for specific items by keyword, GTIN, category, charity, product, image </b><a href=\"/api-docs/static/versioning.html#experimental \" target=\"_blank\"><img src=\"/cms/img/docs/experimental-icon.svg\" class=\"legend-icon experimental-icon\" alt=\"Experimental Method\" title=\"Experimental Method\" />(Experimental Method)</a>, or item aspects and refine the results by using filters, such as aspects, compatibility, and fields values, or UI parameters.</li>   <li><b> item: </b> <ul><li>Lets you retrieve the details of a specific item or all the items in an item group, which is an item with variations such as color and size and check if a product is compatible with the specified item, such as if a specific car is compatible with a specific part.</li> <li>Provides a bridge between the eBay legacy APIs, such as <b> Finding</b>, and the RESTful APIs, which use different formats for the item IDs.</li>  </ul> </li>  </ul>       <p>The <b> item_summary</b>, <b> search_by_image</b>, and <b> item</b> resource calls require an <a href=\"/api-docs/static/oauth-client-credentials-grant.html\">Application access token</a>.</p>
 *
 * OpenAPI spec version: v1.19.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.ebuyer.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.util.Objects;

/**
 * AvailableCoupon
 */

@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-25T17:50:03.851347329Z[GMT]")

public class AvailableCoupon {
  @SerializedName("constraint")
  private CouponConstraint constraint = null;

  @SerializedName("discountAmount")
  private Amount discountAmount = null;

  @SerializedName("discountType")
  private String discountType = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("redemptionCode")
  private String redemptionCode = null;

  @SerializedName("termsWebUrl")
  private String termsWebUrl = null;

  public AvailableCoupon constraint(CouponConstraint constraint) {
    this.constraint = constraint;
    return this;
  }

   /**
   * Get constraint
   * @return constraint
  **/
  @Schema(description = "")
  public CouponConstraint getConstraint() {
    return constraint;
  }

  public void setConstraint(CouponConstraint constraint) {
    this.constraint = constraint;
  }

  public AvailableCoupon discountAmount(Amount discountAmount) {
    this.discountAmount = discountAmount;
    return this;
  }

   /**
   * Get discountAmount
   * @return discountAmount
  **/
  @Schema(description = "")
  public Amount getDiscountAmount() {
    return discountAmount;
  }

  public void setDiscountAmount(Amount discountAmount) {
    this.discountAmount = discountAmount;
  }

  public AvailableCoupon discountType(String discountType) {
    this.discountType = discountType;
    return this;
  }

   /**
   * The type of discount that the coupon applies. For implementation help, refer to &lt;a href&#x3D;&#x27;https://developer.ebay.com/api-docs/buy/browse/types/gct:CouponDiscountType&#x27;&gt;eBay API documentation&lt;/a&gt;
   * @return discountType
  **/
  @Schema(description = "The type of discount that the coupon applies. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/buy/browse/types/gct:CouponDiscountType'>eBay API documentation</a>")
  public String getDiscountType() {
    return discountType;
  }

  public void setDiscountType(String discountType) {
    this.discountType = discountType;
  }

  public AvailableCoupon message(String message) {
    this.message = message;
    return this;
  }

   /**
   * A description of the coupon.&lt;br&gt;&lt;br&gt;&lt;span class&#x3D;\&quot;tablenote\&quot;&gt;&lt;b&gt; Note: &lt;/b&gt; The value returned in the &lt;b&gt;termsWebUrl&lt;/b&gt; field should appear for all experiences when displaying coupons. The value in the &lt;b&gt;availableCoupons.message&lt;/b&gt; field must also be included, if returned in the API response.&lt;/span&gt;
   * @return message
  **/
  @Schema(description = "A description of the coupon.<br><br><span class=\"tablenote\"><b> Note: </b> The value returned in the <b>termsWebUrl</b> field should appear for all experiences when displaying coupons. The value in the <b>availableCoupons.message</b> field must also be included, if returned in the API response.</span>")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public AvailableCoupon redemptionCode(String redemptionCode) {
    this.redemptionCode = redemptionCode;
    return this;
  }

   /**
   * The coupon code.
   * @return redemptionCode
  **/
  @Schema(description = "The coupon code.")
  public String getRedemptionCode() {
    return redemptionCode;
  }

  public void setRedemptionCode(String redemptionCode) {
    this.redemptionCode = redemptionCode;
  }

  public AvailableCoupon termsWebUrl(String termsWebUrl) {
    this.termsWebUrl = termsWebUrl;
    return this;
  }

   /**
   * The URL to the coupon terms of use.&lt;br&gt;&lt;br&gt;&lt;span class&#x3D;\&quot;tablenote\&quot;&gt;&lt;b&gt; Note: &lt;/b&gt; The value returned in the &lt;b&gt;termsWebUrl&lt;/b&gt; field should appear for all experiences when displaying coupons. The value in the &lt;b&gt;availableCoupons.message&lt;/b&gt; field must also be included, if returned in the API response.&lt;/span&gt;
   * @return termsWebUrl
  **/
  @Schema(description = "The URL to the coupon terms of use.<br><br><span class=\"tablenote\"><b> Note: </b> The value returned in the <b>termsWebUrl</b> field should appear for all experiences when displaying coupons. The value in the <b>availableCoupons.message</b> field must also be included, if returned in the API response.</span>")
  public String getTermsWebUrl() {
    return termsWebUrl;
  }

  public void setTermsWebUrl(String termsWebUrl) {
    this.termsWebUrl = termsWebUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AvailableCoupon availableCoupon = (AvailableCoupon) o;
    return Objects.equals(this.constraint, availableCoupon.constraint) &&
        Objects.equals(this.discountAmount, availableCoupon.discountAmount) &&
        Objects.equals(this.discountType, availableCoupon.discountType) &&
        Objects.equals(this.message, availableCoupon.message) &&
        Objects.equals(this.redemptionCode, availableCoupon.redemptionCode) &&
        Objects.equals(this.termsWebUrl, availableCoupon.termsWebUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(constraint, discountAmount, discountType, message, redemptionCode, termsWebUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvailableCoupon {\n");
    
    sb.append("    constraint: ").append(toIndentedString(constraint)).append("\n");
    sb.append("    discountAmount: ").append(toIndentedString(discountAmount)).append("\n");
    sb.append("    discountType: ").append(toIndentedString(discountType)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    redemptionCode: ").append(toIndentedString(redemptionCode)).append("\n");
    sb.append("    termsWebUrl: ").append(toIndentedString(termsWebUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
