/*
 * Browse API
 * <p>The Browse API has the following resources:</p>   <ul> <li><b> item_summary: </b> Lets shoppers search for specific items by keyword, GTIN, category, charity, product, image </b><a href=\"/api-docs/static/versioning.html#experimental \" target=\"_blank\"><img src=\"/cms/img/docs/experimental-icon.svg\" class=\"legend-icon experimental-icon\" alt=\"Experimental Method\" title=\"Experimental Method\" />(Experimental Method)</a>, or item aspects and refine the results by using filters, such as aspects, compatibility, and fields values, or UI parameters.</li>   <li><b> item: </b> <ul><li>Lets you retrieve the details of a specific item or all the items in an item group, which is an item with variations such as color and size and check if a product is compatible with the specified item, such as if a specific car is compatible with a specific part.</li> <li>Provides a bridge between the eBay legacy APIs, such as <b> Finding</b>, and the RESTful APIs, which use different formats for the item IDs.</li>  </ul> </li>  </ul>       <p>The <b> item_summary</b>, <b> search_by_image</b>, and <b> item</b> resource calls require an <a href=\"/api-docs/static/oauth-client-credentials-grant.html\">Application access token</a>.</p>
 *
 * OpenAPI spec version: v1.19.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.ebuyer.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.util.Objects;

/**
 * The container that defines the fields for the category refinements. This container is returned when &lt;b&gt; fieldgroups&lt;/b&gt; is set to &lt;code&gt;CATEGORY_REFINEMENTS&lt;/code&gt; or &lt;code&gt;FULL&lt;/code&gt; in the request.
 */
@Schema(description = "The container that defines the fields for the category refinements. This container is returned when <b> fieldgroups</b> is set to <code>CATEGORY_REFINEMENTS</code> or <code>FULL</code> in the request.")
@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-25T17:50:03.851347329Z[GMT]")

public class CategoryDistribution {
  @SerializedName("categoryId")
  private String categoryId = null;

  @SerializedName("categoryName")
  private String categoryName = null;

  @SerializedName("matchCount")
  private Integer matchCount = null;

  @SerializedName("refinementHref")
  private String refinementHref = null;

  public CategoryDistribution categoryId(String categoryId) {
    this.categoryId = categoryId;
    return this;
  }

   /**
   * The identifier of the category.
   * @return categoryId
  **/
  @Schema(description = "The identifier of the category.")
  public String getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(String categoryId) {
    this.categoryId = categoryId;
  }

  public CategoryDistribution categoryName(String categoryName) {
    this.categoryName = categoryName;
    return this;
  }

   /**
   * The name of the category, such as Baby &amp; Toddler Clothing.
   * @return categoryName
  **/
  @Schema(description = "The name of the category, such as Baby & Toddler Clothing.")
  public String getCategoryName() {
    return categoryName;
  }

  public void setCategoryName(String categoryName) {
    this.categoryName = categoryName;
  }

  public CategoryDistribution matchCount(Integer matchCount) {
    this.matchCount = matchCount;
    return this;
  }

   /**
   * The number of items in this category.
   * @return matchCount
  **/
  @Schema(description = "The number of items in this category.")
  public Integer getMatchCount() {
    return matchCount;
  }

  public void setMatchCount(Integer matchCount) {
    this.matchCount = matchCount;
  }

  public CategoryDistribution refinementHref(String refinementHref) {
    this.refinementHref = refinementHref;
    return this;
  }

   /**
   * The HATEOAS reference of this category.
   * @return refinementHref
  **/
  @Schema(description = "The HATEOAS reference of this category.")
  public String getRefinementHref() {
    return refinementHref;
  }

  public void setRefinementHref(String refinementHref) {
    this.refinementHref = refinementHref;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoryDistribution categoryDistribution = (CategoryDistribution) o;
    return Objects.equals(this.categoryId, categoryDistribution.categoryId) &&
        Objects.equals(this.categoryName, categoryDistribution.categoryName) &&
        Objects.equals(this.matchCount, categoryDistribution.matchCount) &&
        Objects.equals(this.refinementHref, categoryDistribution.refinementHref);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categoryId, categoryName, matchCount, refinementHref);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CategoryDistribution {\n");
    
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    categoryName: ").append(toIndentedString(categoryName)).append("\n");
    sb.append("    matchCount: ").append(toIndentedString(matchCount)).append("\n");
    sb.append("    refinementHref: ").append(toIndentedString(refinementHref)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
