/*
 * Browse API
 * <p>The Browse API has the following resources:</p>   <ul> <li><b> item_summary: </b> Lets shoppers search for specific items by keyword, GTIN, category, charity, product, image </b><a href=\"/api-docs/static/versioning.html#experimental \" target=\"_blank\"><img src=\"/cms/img/docs/experimental-icon.svg\" class=\"legend-icon experimental-icon\" alt=\"Experimental Method\" title=\"Experimental Method\" />(Experimental Method)</a>, or item aspects and refine the results by using filters, such as aspects, compatibility, and fields values, or UI parameters.</li>   <li><b> item: </b> <ul><li>Lets you retrieve the details of a specific item or all the items in an item group, which is an item with variations such as color and size and check if a product is compatible with the specified item, such as if a specific car is compatible with a specific part.</li> <li>Provides a bridge between the eBay legacy APIs, such as <b> Finding</b>, and the RESTful APIs, which use different formats for the item IDs.</li>  </ul> </li>  </ul>       <p>The <b> item_summary</b>, <b> search_by_image</b>, and <b> item</b> resource calls require an <a href=\"/api-docs/static/oauth-client-credentials-grant.html\">Application access token</a>.</p>
 *
 * OpenAPI spec version: v1.19.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.ebuyer.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * The type that defines the response fields for &lt;b&gt; checkCompatibility&lt;/b&gt;.  
 */
@Schema(description = "The type that defines the response fields for <b> checkCompatibility</b>.  ")
@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-25T17:50:03.851347329Z[GMT]")

public class CompatibilityResponse {
  @SerializedName("compatibilityStatus")
  private String compatibilityStatus = null;

  @SerializedName("warnings")
  private List<Error> warnings = null;

  public CompatibilityResponse compatibilityStatus(String compatibilityStatus) {
    this.compatibilityStatus = compatibilityStatus;
    return this;
  }

   /**
   * An enumeration value that tells you if the item is compatible with the product. &lt;br&gt;&lt;br&gt;The values are: &lt;ul&gt;   &lt;li&gt;   &lt;b&gt; COMPATIBLE&lt;/b&gt; - Indicates the item is compatible with the product specified in the request.&lt;/li&gt;   &lt;li&gt;   &lt;b&gt; NOT_COMPATIBLE&lt;/b&gt; - Indicates the item is not compatible with the product specified in the request. Be sure to check all the &lt;b&gt; value&lt;/b&gt; fields to ensure they are correct as errors in the value can also cause this response.&lt;/li&gt;   &lt;li&gt; &lt;b&gt; UNDETERMINED&lt;/b&gt; - Indicates one or more attributes for the specified product are missing so compatibility cannot be determined.  The response returns the attributes that are missing.&lt;/li&gt;  &lt;/ul&gt;  Code so that your app gracefully handles any future changes to this list. For implementation help, refer to &lt;a href&#x3D;&#x27;https://developer.ebay.com/api-docs/buy/browse/types/gct:CompatibilityStatus&#x27;&gt;eBay API documentation&lt;/a&gt;
   * @return compatibilityStatus
  **/
  @Schema(description = "An enumeration value that tells you if the item is compatible with the product. <br><br>The values are: <ul>   <li>   <b> COMPATIBLE</b> - Indicates the item is compatible with the product specified in the request.</li>   <li>   <b> NOT_COMPATIBLE</b> - Indicates the item is not compatible with the product specified in the request. Be sure to check all the <b> value</b> fields to ensure they are correct as errors in the value can also cause this response.</li>   <li> <b> UNDETERMINED</b> - Indicates one or more attributes for the specified product are missing so compatibility cannot be determined.  The response returns the attributes that are missing.</li>  </ul>  Code so that your app gracefully handles any future changes to this list. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/buy/browse/types/gct:CompatibilityStatus'>eBay API documentation</a>")
  public String getCompatibilityStatus() {
    return compatibilityStatus;
  }

  public void setCompatibilityStatus(String compatibilityStatus) {
    this.compatibilityStatus = compatibilityStatus;
  }

  public CompatibilityResponse warnings(List<Error> warnings) {
    this.warnings = warnings;
    return this;
  }

  public CompatibilityResponse addWarningsItem(Error warningsItem) {
    if (this.warnings == null) {
      this.warnings = new ArrayList<Error>();
    }
    this.warnings.add(warningsItem);
    return this;
  }

   /**
   * An array of warning messages. These types of errors do not prevent the method from executing but should be checked.
   * @return warnings
  **/
  @Schema(description = "An array of warning messages. These types of errors do not prevent the method from executing but should be checked.")
  public List<Error> getWarnings() {
    return warnings;
  }

  public void setWarnings(List<Error> warnings) {
    this.warnings = warnings;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompatibilityResponse compatibilityResponse = (CompatibilityResponse) o;
    return Objects.equals(this.compatibilityStatus, compatibilityResponse.compatibilityStatus) &&
        Objects.equals(this.warnings, compatibilityResponse.warnings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(compatibilityStatus, warnings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompatibilityResponse {\n");
    
    sb.append("    compatibilityStatus: ").append(toIndentedString(compatibilityStatus)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
