/*
 * Browse API
 * <p>The Browse API has the following resources:</p>   <ul> <li><b> item_summary: </b> Lets shoppers search for specific items by keyword, GTIN, category, charity, product, image </b><a href=\"/api-docs/static/versioning.html#experimental \" target=\"_blank\"><img src=\"/cms/img/docs/experimental-icon.svg\" class=\"legend-icon experimental-icon\" alt=\"Experimental Method\" title=\"Experimental Method\" />(Experimental Method)</a>, or item aspects and refine the results by using filters, such as aspects, compatibility, and fields values, or UI parameters.</li>   <li><b> item: </b> <ul><li>Lets you retrieve the details of a specific item or all the items in an item group, which is an item with variations such as color and size and check if a product is compatible with the specified item, such as if a specific car is compatible with a specific part.</li> <li>Provides a bridge between the eBay legacy APIs, such as <b> Finding</b>, and the RESTful APIs, which use different formats for the item IDs.</li>  </ul> </li>  </ul>       <p>The <b> item_summary</b>, <b> search_by_image</b>, and <b> item</b> resource calls require an <a href=\"/api-docs/static/oauth-client-credentials-grant.html\">Application access token</a>.</p>
 *
 * OpenAPI spec version: v1.19.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.ebuyer.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * This type displays the value(s) associated with the specified condition descriptor name, as well as any additional information about a condition descriptor. 
 */
@Schema(description = "This type displays the value(s) associated with the specified condition descriptor name, as well as any additional information about a condition descriptor. ")
@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-25T17:50:03.851347329Z[GMT]")

public class ConditionDescriptorValue {
  @SerializedName("additionalInfo")
  private List<String> additionalInfo = null;

  @SerializedName("content")
  private String content = null;

  public ConditionDescriptorValue additionalInfo(List<String> additionalInfo) {
    this.additionalInfo = additionalInfo;
    return this;
  }

  public ConditionDescriptorValue addAdditionalInfoItem(String additionalInfoItem) {
    if (this.additionalInfo == null) {
      this.additionalInfo = new ArrayList<String>();
    }
    this.additionalInfo.add(additionalInfoItem);
    return this;
  }

   /**
   * Additional information about the condition of an item as it relates to a condition descriptor. This array elaborates on the value specified in the &lt;b&gt;content&lt;/b&gt; field and provides additional details about the condition of an item.
   * @return additionalInfo
  **/
  @Schema(description = "Additional information about the condition of an item as it relates to a condition descriptor. This array elaborates on the value specified in the <b>content</b> field and provides additional details about the condition of an item.")
  public List<String> getAdditionalInfo() {
    return additionalInfo;
  }

  public void setAdditionalInfo(List<String> additionalInfo) {
    this.additionalInfo = additionalInfo;
  }

  public ConditionDescriptorValue content(String content) {
    this.content = content;
    return this;
  }

   /**
   * The value for the condition descriptor indicated in the associated &lt;b&gt;name&lt;/b&gt; field.
   * @return content
  **/
  @Schema(description = "The value for the condition descriptor indicated in the associated <b>name</b> field.")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConditionDescriptorValue conditionDescriptorValue = (ConditionDescriptorValue) o;
    return Objects.equals(this.additionalInfo, conditionDescriptorValue.additionalInfo) &&
        Objects.equals(this.content, conditionDescriptorValue.content);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalInfo, content);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConditionDescriptorValue {\n");
    
    sb.append("    additionalInfo: ").append(toIndentedString(additionalInfo)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
