/*
 * Browse API
 * <p>The Browse API has the following resources:</p>   <ul> <li><b> item_summary: </b> Lets shoppers search for specific items by keyword, GTIN, category, charity, product, image </b><a href=\"/api-docs/static/versioning.html#experimental \" target=\"_blank\"><img src=\"/cms/img/docs/experimental-icon.svg\" class=\"legend-icon experimental-icon\" alt=\"Experimental Method\" title=\"Experimental Method\" />(Experimental Method)</a>, or item aspects and refine the results by using filters, such as aspects, compatibility, and fields values, or UI parameters.</li>   <li><b> item: </b> <ul><li>Lets you retrieve the details of a specific item or all the items in an item group, which is an item with variations such as color and size and check if a product is compatible with the specified item, such as if a specific car is compatible with a specific part.</li> <li>Provides a bridge between the eBay legacy APIs, such as <b> Finding</b>, and the RESTful APIs, which use different formats for the item IDs.</li>  </ul> </li>  </ul>       <p>The <b> item_summary</b>, <b> search_by_image</b>, and <b> item</b> resource calls require an <a href=\"/api-docs/static/oauth-client-credentials-grant.html\">Application access token</a>.</p>
 *
 * OpenAPI spec version: v1.19.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.ebuyer.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.util.Objects;

/**
 * A type that defines the pictogram for the type of hazard that a hazardous material represents.
 */
@Schema(description = "A type that defines the pictogram for the type of hazard that a hazardous material represents.")
@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-25T17:50:03.851347329Z[GMT]")

public class HazardPictogram {
  @SerializedName("pictogramDescription")
  private String pictogramDescription = null;

  @SerializedName("pictogramId")
  private String pictogramId = null;

  @SerializedName("pictogramUrl")
  private String pictogramUrl = null;

  public HazardPictogram pictogramDescription(String pictogramDescription) {
    this.pictogramDescription = pictogramDescription;
    return this;
  }

   /**
   * The description of the hazard pictogram, such as Flammable.
   * @return pictogramDescription
  **/
  @Schema(description = "The description of the hazard pictogram, such as Flammable.")
  public String getPictogramDescription() {
    return pictogramDescription;
  }

  public void setPictogramDescription(String pictogramDescription) {
    this.pictogramDescription = pictogramDescription;
  }

  public HazardPictogram pictogramId(String pictogramId) {
    this.pictogramId = pictogramId;
    return this;
  }

   /**
   * The ID of the hazard pictogram.
   * @return pictogramId
  **/
  @Schema(description = "The ID of the hazard pictogram.")
  public String getPictogramId() {
    return pictogramId;
  }

  public void setPictogramId(String pictogramId) {
    this.pictogramId = pictogramId;
  }

  public HazardPictogram pictogramUrl(String pictogramUrl) {
    this.pictogramUrl = pictogramUrl;
    return this;
  }

   /**
   * The URL of the hazard pictogram.
   * @return pictogramUrl
  **/
  @Schema(description = "The URL of the hazard pictogram.")
  public String getPictogramUrl() {
    return pictogramUrl;
  }

  public void setPictogramUrl(String pictogramUrl) {
    this.pictogramUrl = pictogramUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HazardPictogram hazardPictogram = (HazardPictogram) o;
    return Objects.equals(this.pictogramDescription, hazardPictogram.pictogramDescription) &&
        Objects.equals(this.pictogramId, hazardPictogram.pictogramId) &&
        Objects.equals(this.pictogramUrl, hazardPictogram.pictogramUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pictogramDescription, pictogramId, pictogramUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HazardPictogram {\n");
    
    sb.append("    pictogramDescription: ").append(toIndentedString(pictogramDescription)).append("\n");
    sb.append("    pictogramId: ").append(toIndentedString(pictogramId)).append("\n");
    sb.append("    pictogramUrl: ").append(toIndentedString(pictogramUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
