/*
 * Browse API
 * <p>The Browse API has the following resources:</p>   <ul> <li><b> item_summary: </b> Lets shoppers search for specific items by keyword, GTIN, category, charity, product, image </b><a href=\"/api-docs/static/versioning.html#experimental \" target=\"_blank\"><img src=\"/cms/img/docs/experimental-icon.svg\" class=\"legend-icon experimental-icon\" alt=\"Experimental Method\" title=\"Experimental Method\" />(Experimental Method)</a>, or item aspects and refine the results by using filters, such as aspects, compatibility, and fields values, or UI parameters.</li>   <li><b> item: </b> <ul><li>Lets you retrieve the details of a specific item or all the items in an item group, which is an item with variations such as color and size and check if a product is compatible with the specified item, such as if a specific car is compatible with a specific part.</li> <li>Provides a bridge between the eBay legacy APIs, such as <b> Finding</b>, and the RESTful APIs, which use different formats for the item IDs.</li>  </ul> </li>  </ul>       <p>The <b> item_summary</b>, <b> search_by_image</b>, and <b> item</b> resource calls require an <a href=\"/api-docs/static/oauth-client-credentials-grant.html\">Application access token</a>.</p>
 *
 * OpenAPI spec version: v1.19.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.ebuyer.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.util.Objects;

/**
 * PaymentMethodBrand
 */

@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-25T17:50:03.851347329Z[GMT]")

public class PaymentMethodBrand {
  @SerializedName("paymentMethodBrandType")
  private String paymentMethodBrandType = null;

  @SerializedName("logoImage")
  private Image logoImage = null;

  public PaymentMethodBrand paymentMethodBrandType(String paymentMethodBrandType) {
    this.paymentMethodBrandType = paymentMethodBrandType;
    return this;
  }

   /**
   * The payment method brand, such as Visa or PayPal. For implementation help, refer to &lt;a href&#x3D;&#x27;https://developer.ebay.com/api-docs/buy/browse/types/gct:PaymentMethodBrandEnum&#x27;&gt;eBay API documentation&lt;/a&gt;
   * @return paymentMethodBrandType
  **/
  @Schema(description = "The payment method brand, such as Visa or PayPal. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/buy/browse/types/gct:PaymentMethodBrandEnum'>eBay API documentation</a>")
  public String getPaymentMethodBrandType() {
    return paymentMethodBrandType;
  }

  public void setPaymentMethodBrandType(String paymentMethodBrandType) {
    this.paymentMethodBrandType = paymentMethodBrandType;
  }

  public PaymentMethodBrand logoImage(Image logoImage) {
    this.logoImage = logoImage;
    return this;
  }

   /**
   * Get logoImage
   * @return logoImage
  **/
  @Schema(description = "")
  public Image getLogoImage() {
    return logoImage;
  }

  public void setLogoImage(Image logoImage) {
    this.logoImage = logoImage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentMethodBrand paymentMethodBrand = (PaymentMethodBrand) o;
    return Objects.equals(this.paymentMethodBrandType, paymentMethodBrand.paymentMethodBrandType) &&
        Objects.equals(this.logoImage, paymentMethodBrand.logoImage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentMethodBrandType, logoImage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethodBrand {\n");
    
    sb.append("    paymentMethodBrandType: ").append(toIndentedString(paymentMethodBrandType)).append("\n");
    sb.append("    logoImage: ").append(toIndentedString(logoImage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
