/*
 * Browse API
 * <p>The Browse API has the following resources:</p>   <ul> <li><b> item_summary: </b> Lets shoppers search for specific items by keyword, GTIN, category, charity, product, image </b><a href=\"/api-docs/static/versioning.html#experimental \" target=\"_blank\"><img src=\"/cms/img/docs/experimental-icon.svg\" class=\"legend-icon experimental-icon\" alt=\"Experimental Method\" title=\"Experimental Method\" />(Experimental Method)</a>, or item aspects and refine the results by using filters, such as aspects, compatibility, and fields values, or UI parameters.</li>   <li><b> item: </b> <ul><li>Lets you retrieve the details of a specific item or all the items in an item group, which is an item with variations such as color and size and check if a product is compatible with the specified item, such as if a specific car is compatible with a specific part.</li> <li>Provides a bridge between the eBay legacy APIs, such as <b> Finding</b>, and the RESTful APIs, which use different formats for the item IDs.</li>  </ul> </li>  </ul>       <p>The <b> item_summary</b>, <b> search_by_image</b>, and <b> item</b> resource calls require an <a href=\"/api-docs/static/oauth-client-credentials-grant.html\">Application access token</a>.</p>
 *
 * OpenAPI spec version: v1.19.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.ebuyer.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import javax.annotation.processing.Generated;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * The type that defines the fields for the rating of a product review.
 */
@Schema(description = "The type that defines the fields for the rating of a product review.")
@Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-01-25T17:50:03.851347329Z[GMT]")

public class ReviewRating {
  @SerializedName("averageRating")
  private String averageRating = null;

  @SerializedName("ratingHistograms")
  private List<RatingHistogram> ratingHistograms = null;

  @SerializedName("reviewCount")
  private Integer reviewCount = null;

  public ReviewRating averageRating(String averageRating) {
    this.averageRating = averageRating;
    return this;
  }

   /**
   * The average rating given to a product based on customer reviews.
   * @return averageRating
  **/
  @Schema(description = "The average rating given to a product based on customer reviews.")
  public String getAverageRating() {
    return averageRating;
  }

  public void setAverageRating(String averageRating) {
    this.averageRating = averageRating;
  }

  public ReviewRating ratingHistograms(List<RatingHistogram> ratingHistograms) {
    this.ratingHistograms = ratingHistograms;
    return this;
  }

  public ReviewRating addRatingHistogramsItem(RatingHistogram ratingHistogramsItem) {
    if (this.ratingHistograms == null) {
      this.ratingHistograms = new ArrayList<RatingHistogram>();
    }
    this.ratingHistograms.add(ratingHistogramsItem);
    return this;
  }

   /**
   * An array of containers for the product rating histograms that shows the review counts and the product rating.
   * @return ratingHistograms
  **/
  @Schema(description = "An array of containers for the product rating histograms that shows the review counts and the product rating.")
  public List<RatingHistogram> getRatingHistograms() {
    return ratingHistograms;
  }

  public void setRatingHistograms(List<RatingHistogram> ratingHistograms) {
    this.ratingHistograms = ratingHistograms;
  }

  public ReviewRating reviewCount(Integer reviewCount) {
    this.reviewCount = reviewCount;
    return this;
  }

   /**
   * The total number of reviews for the item.
   * @return reviewCount
  **/
  @Schema(description = "The total number of reviews for the item.")
  public Integer getReviewCount() {
    return reviewCount;
  }

  public void setReviewCount(Integer reviewCount) {
    this.reviewCount = reviewCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReviewRating reviewRating = (ReviewRating) o;
    return Objects.equals(this.averageRating, reviewRating.averageRating) &&
        Objects.equals(this.ratingHistograms, reviewRating.ratingHistograms) &&
        Objects.equals(this.reviewCount, reviewRating.reviewCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(averageRating, ratingHistograms, reviewCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReviewRating {\n");
    
    sb.append("    averageRating: ").append(toIndentedString(averageRating)).append("\n");
    sb.append("    ratingHistograms: ").append(toIndentedString(ratingHistograms)).append("\n");
    sb.append("    reviewCount: ").append(toIndentedString(reviewCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
